### ISSUE TITLE
Tools for migrations

### ISSUE THREAD

**Issue by asgerhallas** [asgerhallas/HybridDb#19]
There are two types of migrations:

1. Changes to model
Migration will be applied on load of the document. And a background process will also process the documents continuously while the application runs.

If you change your model you will have to write a DocumentMigration that that manipulates the JSON document before it is deserialized. 

2. Changes to projections
Changes to tables will be applied upon application startup, and a background process will open each document and update projections continuously while the application runs.

When application starts HybridDb reads schema version from each table by getting MAX value of the schema version column. 

If there are changes to the configuration it does the following:

- New document base type: Creates tables and columns
- New projections on existing document types: Creates column and opens each document to update projection
- Remove projection: Drops column
- Rename projection: Acts as a remove and an add (see below for renaming of columns)

If there are other changes to the configuration, that can not be automatically detected, eg. a getter returns a new value or a porjection is configured differently but with same name as before, then the user should add a special DocumentMigration named ForceProjectionUpdate, which opens each document to update projection.

Migrations for other schema changes (drop table, rename column) are still under consideration. The problem is that it should only be run once, but there is no obvious way to detect if it has been done. One solution is to have an external table for handling schema versions. 

Migration for moving documents to other tables might be needed too.

**Comment by asgerhallas** [comment]
We are making a different migration system.

**Comment by mookid8000** [comment]
how do you solve migration of huge amounts of documents then?

**Comment by asgerhallas** [comment]
No one was supposed to be looking :D
It will be reopened with a different description of the same solution. Or something like that.

**Comment by mookid8000** [comment]
right..... ¯\_(ツ)_/¯

**Comment by asgerhallas** [comment]
Done and running in production!

**Comment by mookid8000** [comment]
:+1:
