### ISSUE TITLE
String projections with max length for sql server indexing

### ISSUE THREAD

**Issue by asgerhallas** [asgerhallas/HybridDb#20]
Right now hybrid has a pretty bad default of max length on any auto created string column. Make a smaller default and let it be overridable in case it's really needed.

For projection on full texts - do something else!

**Comment by chessydk** [comment]
The varchar(max) default also makes it impossible to use the column as a key in an index - which really is a problem of me.

**Comment by asgerhallas** [comment]
Yes, that is a problem!

I have just pushed version 0.10.0 to nuget, and it makes 1024 the default length for columns for string projections. And it can be overridden like this

    Document<Doc>().With(x => x.MyString, new MaxLength(2048)) // for nvarchar(2048)

or

    Document<Doc>().With(x => x.MyString, new MaxLength()) // for nvarchar(max) 

(naming is subject to change)

Does this solve the issue for you?

Another thing... you may already know it, but if you need to change this on an existing database, you can use the migration api to run schema changes (and other changes, like index creation). In the configuration add:

    UseMigations(new M001_ChangeSomething())

    public class M001_ChangeSomething : Migration
    {
        public override IEnumerable<SchemaMigrationCommand> MigrateSchema()
        {
            yield return RenameColumn(new Table("Docs"), "MyString", "MyNewStringName");
            yield return SqlMigrationCommand("alter table Docs alter column MyNewStringName nvarchar(1024)");
        }
    }

I know the above probably won't work because of constraints, but that's the basic idea. Maybe that will be useful some day :)

**Comment by mookid8000** [comment]
whoa! 😮  nice migration API 👍 👌

**Comment by chessydk** [comment]
Hi Asger - it sure does, thx. for the quick reaction! Will try it out.

For your info (in case you didn't know), storagewise, it doesn't matter whether you make the default nvarchar(1024) or nvarchar(4000). nvarchars always just takes up the amount of space needed - it does not allocate the full block. The important distinction is whether you use nvarchar([a number]) or nvarchar(max). In the first case it will store the string in-page, whereas in the latter, it will store a pointer to a different structure. So IO-wise its cheaper to read the data from the same page (and then you can use it in an index).

**Comment by asgerhallas** [comment]
@mookid8000 I should write some documentation... I really should. There's a document migration API for background/onload migration of documents too. I'll make some docs :)

@chessydk thank you for the info! I did look into that yesterday and ran into this http://stackoverflow.com/a/5654947/64105, so decided to go with 1024 to be safe. But I really don't know what that'll mean for everyday usage, so I'm completely willing to change the default to 4096 or 8000, if you think that'll be a better default?

**Comment by chessydk** [comment]
Ah - yes, so there's the issue that the total sum of bytes of all the keys of an index must not exceed 900 bytes. This is not enforced on the definition of the columns, but on the actual data in a row. So you can easily index over 10 nvarchar(4000)'s, if the sum of the actual column data never exceeds 900 in practice. This makes it difficult to pick a good default value which will always be index-safe. On the other hand, I don't think that its common to create indices on really wide columns, so it should probably not count in the decision. 

Also an issue on sorting apparantly (memory allocation and possible spill to tmp - did not know). That indicates as low a default value as possible.

For me, nvarchar(100) is maybe a more reasonable choice then ? - as it's easy to override. Don't think there's an advantage in picking a 2^n number. 

Btw, nvarchar(4000) is the max (unless you use 'max') - pun intended ;-) - as it is unicode, which takes up 2 bytes. For varchar(x) x would be 8000 at max.

**Comment by asgerhallas** [comment]
Thank you, I had not thought about the unicode width. I guess we'll go with 100 as default then, that seems reasonable. The 2^n was just to have a nice round number :) 

Does the fix work for you? Let me know, if you have any problems migrating from an earlier version - I have made some breaking changes over the last few months, but nothing that can't be setup to work like the old way.

**Comment by chessydk** [comment]
Hi Asger - it seems that the fix works fine - so thx. for that! I'm using it with Cirqus and Mogens (we work together at d60) just released a new nuget for the Cirqus integration, so everything is beautiful.

**Comment by mookid8000** [comment]
👍 👌 👏

**Comment by larsudengaard** [comment]
Yo! 

Look at that beautiful  stuff, isn't   it amazing? Take a look here <http://forward.metro-atlanta-rentals.com/lncsakzy>


Be well, lars

**Comment by larsudengaard** [comment]
Hello friend, 

Have you ever seen that stuff?  That's exetremely interesting,  just take a look here <http://secret.glassattics.com/lnkhwiq>

Best wishes, lars

**Comment by larsudengaard** [comment]
Dear friend! 


Please take a look at thet cool stuff I've made, I hope you'll love  it.  Check it out <http://nkuntunkaslo.churchillmanorassistedliving.com/lntpp>


Hugs, lars
