### ISSUE TITLE
Cannot use same Id in different tables

### ISSUE THREAD

**Issue by asgerhallas** [asgerhallas/HybridDb#21]
The session manages loaded documents by id, but forgets that two different types can have same id.

**Comment by mookid8000** [comment]
Any idea when #33 will be released? :grin:

**Comment by asgerhallas** [comment]
it's building as we speak :)

**Comment by asgerhallas** [comment]
@mookid8000 aaaaand it's out as 0.8.4

**Comment by mookid8000** [comment]
beautiful! :+1:
