### ISSUE TITLE
Simplify indexes

### ISSUE THREAD

**Issue by asgerhallas** [asgerhallas/HybridDb#26]
Have indexes always in the same table as the document for simplicity, as opposed to today where you can have a separate index table if you want.

Support configuration of document subtypes in the same table.

**Comment by mookid8000** [comment]
Do you support multikey indexes?

**Comment by asgerhallas** [comment]
We're working on that (#8)... That will probably still be a seperate table, though :)

**Comment by mookid8000** [comment]
or an XML column?

**Comment by asgerhallas** [comment]
I was reading about those - superficially - and some people adviced against it, but I will have to read some more about it, I guess. One thing is for sure, the IDocumentStore implementations should be able to implement it differently for different stores...

**Comment by asgerhallas** [comment]
But it sure looks like an easy and simple solution, maybe I should just try it.

@larsudengaard and I are trying to give HybridDb a brush up, so we can use it for Cirqus views too among other things... as per your suggestion :)
