### ISSUE TITLE
Revert back to using JSON for document storage

### ISSUE THREAD

**Issue by asgerhallas** [asgerhallas/HybridDb#27]

**Comment by mookid8000** [comment]
:+1:

but why?

**Comment by asgerhallas** [comment]
You think the description of the issue lacks some detail? :)

Well, my reasons are the following:

1. Convenience. It would be nice to be able to just look at and copy/paste directly from SSMS. And for debugging in HybridDb itself it would be convenient too, to have a readable format. 

2. Faster/smaller. Our original reason for using BSON was that we measured it to de-/serialize faster than JSON, but that does no longer seem to be the case for Newtonsofts serializer for the most common use cases. And the smaller size of JSON-documents is more relevant than we anticipated - we are working with quite large documents in some scenarios and our db is growing rapidly. And I guess transfer speed would be better too, but I would need to measure that.

3. Faster document migrations. For in-process migration of documents we are required to deserialize twice - one from BSON to JObjects then after modifications are made on to object instances. If we had JSON directly from the store, we could manipulate that directly in some scenarios to gain speed.

4. The new JSON-column type in SQL Server 2016. Wouldn't it be nice to leverage that? :)

5. Patching. That's something I've thought about for a long time. We are saving large documents to SQL Server and we do it over and over again with very small changes. That results in a very large transaction log. In many cases we have to go for simple recovery model and live with the many drawbacks of that. If we could - for small updates - just send a patch to the document and have that applied using the .write clause, that would be great. But the length prefixes in BSON-data make it quite hard to do that. Yes, making a proper diff from the one doc to another will be hard and potentially not that performant, but it might be worth a try.

But there might be reasons to keep the current format too, and I would very much like to talk it through with you some day :)

**Comment by hdrachmann** [comment]
+1 (for debugging)

**Comment by mookid8000** [comment]
First thing I did when I introduced HybriDB on a project: Use my own Newtonsoft-based JSON serializer.... very convenient that you can
 
    select cast(Document as xml) from SomeTable

**Comment by asgerhallas** [comment]
It has been done. A long time ago. But now it also uses a nvarchar(max) column for storage so we're ready to make use of SQL Servers JSON features.
