### ISSUE TITLE
Consider upgrading dependencies...

### ISSUE THREAD

**Issue by mookid8000** [asgerhallas/HybridDb#35]
because you are compiling against [Serilog 1.4.204](https://github.com/asgerhallas/HybridDb/blob/master/src/HybridDb/packages.config#L6) (which is pretty old) and [Newtonsoft JSON 6.0.8](https://github.com/asgerhallas/HybridDb/blob/master/src/HybridDb/packages.config#L5) (which is also pretty old).

At the moment it is not possible to run HybridDB with Serilog 2 without getting a `MissingMethodException` because the internal `Configuration` ctor attempts to initialize Serilog.

**Comment by mookid8000** [comment]
In case you're interested, I have submitted #36 – feel free to close it if you are not ready to upgrade Serilog

**Comment by asgerhallas** [comment]
I'm so ready!

**Comment by asgerhallas** [comment]
On nuget as 0.10.5 in a few minutes...
